telecom:
  target: "{{ env_var('DBT_TARGET', 'prd') }}"
  outputs:

    dev:
      type: bigquery
      method: service-account
      project: telecombr-dev
      dataset: telecom_dev
      keyfile: "{{ env_var('GCP_KEYFILE_DEV', 'credentials/gcp_credentials_dev.json') }}"
      location: US
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive

    prd:
      type: bigquery
      method: service-account
      project: telecombr-prd
      dataset: telecom_prod
      keyfile: "{{ env_var('GCP_KEYFILE_PRD', 'credentials/gcp_credentials_prd.json') }}"
      location: US
      threads: 4
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: batch
